"""Create database

Revision ID: 44da48f2f781
Revises: addcc70476bd
Create Date: 2024-11-25 20:50:51.013713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44da48f2f781'
down_revision: Union[str, None] = 'addcc70476bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attachment', 'user', ['uploaded_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'uploaded_by')
    # ### end Alembic commands ###
